import React from 'react';
import Head from 'next/head';
import { CloseIcon } from 'assets/images/common';
import css from './fast-start.module.scss';

const FastStartLayout = ({ children }: { children: any }) => {
    return (
        <><Head>
            <title>RXP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="" />
        </Head>
            <section>
                <div className={`${css['fast-start']}`} >
                    <div className='row p-0 m-0'>
                        <div className={`mt-33 ${css.close}`}>
                            <CloseIcon />
                        </div>
                        {children}
                    </div>
                </div>
            </section>
        </>
    );
};

export default FastStartLayout;

