
export const API = {
    posts: 'posts',
    advantages:  'advantages',
    report: 'reports',
    news: 'news',
    rewards: 'awards',
    aboutUs: 'aboutUs',
    developmentGoals: 'developmentGoals',
    categories: 'categories',
    services: 'servicesSelected',
    selectedServices: 'selectedServices',
    usefulLinks: 'useFulLinks',
    fastStart: 'fastStart',
    servicesByFastStartId: 'servicesByFastStartId',
    institutions: 'institutions',
    statistics: 'statistics',
    apllyTopics: 'toApplySubjects',
    callOrder: 'orderCall',
    checkOrderCallOtp: 'checkOrderCallOtp',
    sendApplication: 'toApply',
    orgServices: 'services',
    servicesByCategoryId: 'servicesByCategoryId',
    otherInstitutions: 'otherInstitutions',
    login: 'api/v1/login',
};
