import React from 'react';
import HeaderComponent from './components/header/header.component';
import FooterComponent from './components/footer/footer.component';
import Head from 'next/head';

interface JSX {
    IntrinsicElements: any;
}

const PublicComponent = ({ children }: { children: any }) => {
   return (
        <><Head>
            <title>RXP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="" />
            
        </Head>
            <div className={`layout container-fluid p-0`}>
                <HeaderComponent />
                    {children}
                <FooterComponent/>
            </div>
        </>
    );
};

export default PublicComponent;

